/* AUTO-GENERATED by build.js — do not edit by hand.
 * The NON-CMS static pages of /sitemap.xml — i.e. root .html files that have no
 * counterpart under pages/ and are therefore not in COMPILED_PAGES.
 *
 * api/sitemap.js merges three sources: the CMS marketing pages (from
 * COMPILED_PAGES + their Mongo sitemap settings), THESE static pages, and the
 * published blog posts from MongoDB. A page listed here AND in COMPILED_PAGES
 * would appear in the sitemap twice, so build.js excludes the CMS pages.
 */
export const STATIC_URLS = [
  {
    "loc": "https://www.davnoot.com/ai-seo-agency.html",
    "lastmod": "2026-07-14",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/ai-seo-montreal.html",
    "lastmod": "2026-07-14",
    "priority": "0.8",
    "changefreq": "monthly"
  }
];
