/* AUTO-GENERATED by build.js — do not edit by hand.
 * The static half of /sitemap.xml. api/sitemap.js merges this with the
 * published blog posts from MongoDB at request time.
 */
export const STATIC_URLS = [
  {
    "loc": "https://www.davnoot.com/",
    "lastmod": "2026-07-14",
    "priority": "1.0",
    "changefreq": "weekly"
  },
  {
    "loc": "https://www.davnoot.com/seo.html",
    "lastmod": "2026-07-14",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/meta-ads.html",
    "lastmod": "2026-07-14",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/email.html",
    "lastmod": "2026-07-14",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/ai-seo.html",
    "lastmod": "2026-07-14",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/chatgpt-ads.html",
    "lastmod": "2026-07-14",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/software.html",
    "lastmod": "2026-07-14",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/ai-seo-montreal.html",
    "lastmod": "2026-07-14",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/book-call.html",
    "lastmod": "2026-07-14",
    "priority": "0.7",
    "changefreq": "monthly"
  }
];
