/* AUTO-GENERATED by build.js — do not edit by hand.
 * The NON-CMS static pages of /sitemap.xml — i.e. root .html files that have no
 * counterpart under pages/ and are therefore not in COMPILED_PAGES.
 *
 * api/sitemap.js merges three sources: the CMS marketing pages (from
 * COMPILED_PAGES + their Mongo sitemap settings), THESE static pages, and the
 * published blog posts from MongoDB. A page listed here AND in COMPILED_PAGES
 * would appear in the sitemap twice, so build.js excludes the CMS pages.
 */
export const STATIC_URLS = [
  {
    "loc": "https://www.davnoot.com/services/shopify",
    "lastmod": "2026-07-22",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/ads",
    "lastmod": "2026-07-22",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/ai-seo-agency",
    "lastmod": "2026-07-22",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/ai-seo-montreal",
    "lastmod": "2026-07-22",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/ads/amazon-ads",
    "lastmod": "2026-07-22",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/etf-marketing",
    "lastmod": "2026-07-22",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/ads/pinterest-ads",
    "lastmod": "2026-07-22",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/privacy",
    "lastmod": "2026-07-22",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/ads/reddit-ads",
    "lastmod": "2026-07-22",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/services",
    "lastmod": "2026-07-22",
    "priority": "0.8",
    "changefreq": "monthly"
  },
  {
    "loc": "https://www.davnoot.com/ads/spotify-ads",
    "lastmod": "2026-07-22",
    "priority": "0.8",
    "changefreq": "monthly"
  }
];
