/* Davnoot — shared site chrome & SEO templates.
 *
 * SINGLE SOURCE OF TRUTH for nav, footer, and the SEO <head>.
 *
 * Two consumers:
 *   1. build.js          — bakes these into the static .html marketing pages.
 *   2. api/blog/*.js     — server-renders them into the blog pages.
 *
 * Because both import from here, the blog can never drift from the marketing
 * site. Change the nav in one place and `node build.js` + the next blog render
 * both pick it up.
 *
 * ---------------------------------------------------------------------------
 * Asset URLs are ROOT-ABSOLUTE
 * ---------------------------------------------------------------------------
 * Inter-page LINKS are absolute and extensionless (/seo, / for home). ASSET srcs
 * (the logo image, favicon) are now root-absolute too — "/images/davnoot-logo.png",
 * not "images/…" — because marketing pages are served one level deep under
 * /services/*, where a relative "images/…" resolves to "/services/images/…" and
 * 404s. Absolute paths are depth-independent and work at /, /services/*, and /blog/*.
 *
 * The `base` parameter is therefore VESTIGIAL for output, but retained in the
 * navHtml/footerHtml signatures because callers pass settings positionally after it
 * (e.g. composed-render's `navHtml('composed', '/', settings)`).
 */

// The site-wide JSON-LD builder. This creates a templates.js <-> structured-data.js
// import cycle; it is SAFE because neither module uses the other's exports at module
// EVALUATION time — only inside functions that run later (see structured-data.js's
// header). Do not add a top-level call to buildGraph() (or a top-level use of a
// structured-data export) here, or the cycle becomes a temporal-dead-zone crash.
import { buildGraph } from './structured-data.js';
// Today's chrome constants, as a committed default. The settings screen edits a diff
// over these; mergeSettings(diff) yields the effective values. No diff -> these exact
// values -> byte-identical output. site-defaults.js imports nothing, so no cycle.
import { SITE_DEFAULTS } from './site-defaults.js';
// Generated by scripts/i18n.js. Imports nothing itself, so no cycle.
import { FULLY_TRANSLATED } from './i18n/coverage.gen.js';

// ---- Site config -----------------------------------------------------------
export const SITE_URL = 'https://www.davnoot.com'; // canonical host (www; matches GSC + Vercel apex→www 308)
export const LOGO = 'images/davnoot-logo.png';
export const OG_IMAGE = SITE_URL + '/' + LOGO;

/* ---- Locales ---------------------------------------------------------------
 * French lives at a PATH PREFIX on the same host (/fr/services/seo), not on a
 * subdomain: davnoot.com's authority is one property, and splitting it would make
 * the French side start from near zero in a market we actually care about.
 *
 * EVERY locale-aware function below defaults to 'en' and, at that default, returns
 * BYTE-IDENTICAL output to the pre-i18n version. That is not politeness — the
 * golden fixtures pin the English bytes, so a signature change that shifted a
 * single character of English would fail `npm run site`. Locale is always the LAST
 * parameter for the same reason (existing positional callers keep working).
 */
export const LOCALES = ['en', 'fr'];
export const DEFAULT_LOCALE = 'en';
export const localePrefix = (locale) => (locale === DEFAULT_LOCALE || !locale ? '' : '/' + locale);
export const otherLocale = (locale) => (locale === 'fr' ? 'en' : 'fr');

/* The pages that EXIST in French — MEASURED, not declared.
 *
 * lib/i18n/coverage.gen.js is written by scripts/i18n.js and lists exactly the
 * pages whose every translatable string has a French entry. Publishing a page at
 * 92% would mean telling Google "this is the French version of /services/seo"
 * about a page that is still mostly the English one — a near-duplicate submitted
 * under an hreflang annotation, which is the precise failure hreflang prevents.
 *
 * This set is also what stops the French nav from linking into a 404: a French
 * visitor clicking "Services" while /fr/services does not exist is sent to the
 * ENGLISH /services rather than a dead URL (see hrefFor). Because nav, footer,
 * switcher, hreflang and the sitemap all read THIS, finishing a page's dictionary
 * entries adds it to the French site everywhere at once — and there is no second
 * list anyone has to remember to update.
 */
export const TRANSLATED_PAGES = new Set(FULLY_TRANSLATED);

export const hasTranslation = (file, locale) =>
  locale === DEFAULT_LOCALE || TRANSLATED_PAGES.has(file);

/* The UI chrome strings. Body copy is translated by scripts/i18n.js from
 * lib/i18n/fr.json; these are the nav/footer strings that build.js GENERATES, so
 * they can only live in code — anything the codemod wrote into the BUILD regions
 * would be overwritten on the next build.
 *
 * Quebec French, not France French: "Blogue" (not "Blog"), "Courriel" (not
 * "Email"), "FNB" (not "ETF"). This is the market these pages are for.
 */
const UI = {
  en: {
    services: 'Services', ads: 'Ads', process: 'Process', work: 'Work',
    blog: 'Blog', contact: 'Contact',
    bookCall: 'Book a call →', jumpForm: 'Jump to form →',
    toggleMenu: 'Toggle menu',
    tagline: 'Independent growth agency. Built for <em>revenue</em>.',
    colServices: 'Services', colCompany: 'Company', colSpecialties: 'Specialties', colContact: 'Contact',
    ecommerce: 'Ecommerce', adPlatforms: 'Ad Platforms', seo: 'SEO', googleAds: 'Google Ads',
    metaAds: 'Meta Ads', email: 'Email', aiSeo: 'AI SEO', chatgptAds: 'ChatGPT Ads',
    software: 'Custom Software', shopify: 'Shopify', shopifySeo: 'Shopify SEO', klaviyo: 'Klaviyo',
    about: 'About', aiSeoAgency: 'AI SEO Agency', aiSeoMontreal: 'AI SEO Montreal', etf: 'ETF Marketing',
    startupSeo: 'Startup SEO', ppcMontreal: 'PPC Agency Montreal', smallBizAds: 'Google Ads for Small Business',
    dentalAds: 'Google Ads for Dentists', legalAds: 'Google Ads for Law Firms',
    rights: '© 2025 Davnoot. All rights reserved.', privacy: 'Privacy Policy',
    builtIn: 'Built with intent in Montreal',
    switchTo: 'FR', switchLabel: 'Voir cette page en français',
  },
  fr: {
    services: 'Services', ads: 'Publicités', process: 'Processus', work: 'Réalisations',
    blog: 'Blogue', contact: 'Contact',
    bookCall: 'Réserver un appel →', jumpForm: 'Aller au formulaire →',
    toggleMenu: 'Afficher le menu',
    tagline: 'Agence de croissance indépendante. Conçue pour le <em>revenu</em>.',
    colServices: 'Services', colCompany: 'Entreprise', colSpecialties: 'Spécialités', colContact: 'Contact',
    ecommerce: 'Commerce en ligne', adPlatforms: 'Plateformes publicitaires', seo: 'Référencement (SEO)',
    googleAds: 'Google Ads', metaAds: 'Meta Ads', email: 'Courriel', aiSeo: 'Référencement IA',
    chatgptAds: 'Publicités ChatGPT', software: 'Logiciels sur mesure', shopify: 'Shopify',
    shopifySeo: 'Référencement Shopify', klaviyo: 'Klaviyo',
    about: 'À propos', aiSeoAgency: 'Agence de référencement IA', aiSeoMontreal: 'Référencement IA Montréal',
    etf: 'Marketing de FNB', startupSeo: 'Référencement pour startups',
    ppcMontreal: 'Agence PPC Montréal', smallBizAds: 'Google Ads pour PME',
    dentalAds: 'Google Ads pour dentistes', legalAds: 'Google Ads pour avocats',
    rights: '© 2025 Davnoot. Tous droits réservés.', privacy: 'Politique de confidentialité',
    builtIn: 'Conçu avec intention à Montréal',
    switchTo: 'EN', switchLabel: 'View this page in English',
  },
};
export const t = (locale, key) => (UI[locale] || UI.en)[key] ?? UI.en[key];

/**
 * The favicon block — ONE source of truth, emitted by every renderer that writes a
 * <head> (seoHtml here, blog-render, blog-404, composed-render, and the hand-written
 * /admin + /seoteam shells).
 *
 * Do NOT point these at LOGO. That file is 579x424 with a transparent background,
 * and both of those facts break it as an icon:
 *   - Google only renders a favicon in search results when it is SQUARE (it wants a
 *     multiple of 48px). A non-square icon is dropped and the generic globe is shown
 *     instead — which is what /reddit-ads-montreal and friends were getting.
 *   - A black mark on transparency vanishes in a dark browser tab.
 * The square, opaque set these tags reference is generated from LOGO by
 * `npm run favicon` (scripts/gen-favicon.js) and committed.
 *
 * /favicon.ico is also present at the web root because Google and every browser probe
 * that path directly when a page declares no icon at all (e.g. a raw 404 or an API
 * response), and it is the only icon path some SERP surfaces will look for.
 *
 * The `sizes` values are LOAD-BEARING METADATA, not decoration: a consumer picks which
 * icon to fetch from this attribute WITHOUT downloading any of them. Two consequences
 * this list is shaped around:
 *   - /favicon.ico is a multi-resolution container holding 16, 32 AND 48 (see ICO_SIZES
 *     in scripts/gen-favicon.js). Declaring only "32x32" hid the 48 entry — the one size
 *     Google actually documents — behind a claim that the file didn't have it.
 *   - 48/96/192 are the multiples of 48 Google asks for. favicon-48x48.png was being
 *     generated and then referenced by nothing, so the smallest compliant PNG on disk
 *     was never offered. It is listed now.
 * Keep this ascending by size, and keep it honest: if gen-favicon.js's output sizes
 * change, these attributes change with them (scripts/invariants.test.js pins that).
 */
export const FAVICON_TAGS = [
  '<link rel="icon" href="/favicon.ico" sizes="16x16 32x32 48x48" />',
  '<link rel="icon" type="image/png" sizes="48x48" href="/images/favicon-48x48.png" />',
  '<link rel="icon" type="image/png" sizes="96x96" href="/images/favicon-96x96.png" />',
  '<link rel="icon" type="image/png" sizes="192x192" href="/images/favicon-192x192.png" />',
  '<link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png" />',
  '<link rel="manifest" href="/site.webmanifest" />',
];
export const ORG_DESC =
  'Davnoot is an independent growth agency. Six disciplines: SEO, paid social, email, AI search, ChatGPT ads, and custom software. Engineered into one revenue engine.';

export const SERVICE_PAGES = ['seo.html', 'google-ads.html', 'meta-ads.html', 'email.html', 'ai-seo.html', 'chatgpt-ads.html', 'software.html', 'shopify.html', 'shopify-seo.html', 'klaviyo.html'];
// The /ads/* namespace: per-platform paid-advertising hub pages. Same shape as
// SERVICE_PAGES (root-only static files served at a namespaced clean URL) but under
// /ads/<name> instead of /services/<name>. The /ads overview (ads.html) is NOT a
// member — it's a flat page served at /ads, like services.html at /services.
export const ADS_PAGES = ['reddit-ads.html', 'pinterest-ads.html', 'amazon-ads.html', 'spotify-ads.html'];
// A FULL service page served at a FLAT URL — currently EMPTY. google-ads.html was
// the only member; on 2026-07-31 it moved into SERVICE_PAGES so it is served at
// /services/google-ads like every other service (the old flat /google-ads 301s
// there). The list stays because the mechanism is the only way to have a page be a
// service to schema and nav while cleanPath() leaves it at the top level:
// membership in SERVICE_PAGES is exactly what adds the /services/ prefix, so a page
// that wants both would have to live here instead, and get its schemaTypeFor() ->
// 'service' and nav active state from the branches below. Routing for such a page
// is the plain flat pair (redirect /<name>.html -> /<name>, rewrite /<name> ->
// /<name>.html), already covered by vercel-config.test.js's "otherwise" branch.
export const FLAT_SERVICE_PAGES = [];
export const SERVICE_TYPE = {
  'seo.html': 'Search Engine Optimization',
  'meta-ads.html': 'Meta Ads Management (Facebook & Instagram)',
  'google-ads.html': 'Google Ads Management',
  'email.html': 'Email Marketing',
  'ai-seo.html': 'AI Search Optimization',
  'chatgpt-ads.html': 'ChatGPT Ads and AI Advertising',
  'software.html': 'Custom Software Development',
  'shopify.html': 'Shopify Development',
  'shopify-seo.html': 'Shopify SEO',
  'klaviyo.html': 'Klaviyo Email and SMS Marketing',
  'reddit-ads.html': 'Reddit Ads Management',
  'pinterest-ads.html': 'Pinterest Ads Management',
  'amazon-ads.html': 'Amazon Ads Management',
  'spotify-ads.html': 'Spotify Ads Management',
};

// Per-page meta keywords. Modern search engines largely ignore this tag for
// ranking, but it's still a low-cost, self-documenting signal (and some AI
// crawlers / internal search read it). Keep each list tight and page-specific —
// 6–10 terms that mirror the title, H1, and body. Pages with no entry get none.
export const KEYWORDS = {
  'index.html': [
    'growth marketing agency', 'digital marketing agency Montreal', 'SEO agency',
    'paid social advertising', 'email marketing', 'AI search optimization',
    'ChatGPT ads', 'custom software development', 'revenue marketing',
  ],
  'seo.html': [
    'SEO agency Montreal', 'technical SEO services', 'SEO audit',
    'keyword strategy', 'on-page optimization', 'link building',
    'organic search growth', 'search engine optimization',
  ],
  'meta-ads.html': [
    'Meta ads agency Montreal', 'Facebook ads agency', 'Meta Ads management',
    'Facebook ads Montreal', 'Instagram ads Montreal', 'Instagram ads',
    'paid social advertising', 'Advantage+ campaigns', 'creative testing',
    'bilingual ad campaigns Montreal', 'performance marketing Montreal',
  ],
  // The PLATFORM page. It owns every Google-branded term — Google Ads, Performance
  // Max, Shopping, Quality Score — including the "<term> Montreal" variants, since
  // its own title targets "Google Ads Montreal". It does NOT own the PPC-worded
  // terms: 'PPC agency Montreal' moved to ppc-agency-montreal.html on 2026-08-11,
  // which targets it in its own title and H1. Nor does it own the audience terms
  // ("for dentists", "for law firms", "for small business") — those are the three
  // vertical pages below. Two of our own pages chasing one query is how you split
  // your own ranking signal.
  'google-ads.html': [
    'Google Ads management Montreal', 'Google Ads Montreal', 'Google Ads agency Montreal',
    'Google Ads management', 'Performance Max campaigns',
    'Google Shopping ads', 'paid search Montreal', 'certified Google Ads agency',
  ],
  // ---- The Google Ads / PPC cluster added 2026-08-11 -------------------------
  // Four pages hanging off /services/google-ads: one management page fenced to the
  // PPC wording, three audience pages fenced to their vertical. The fence line is
  // the WORD, not the topic: google-ads.html keeps "Google Ads <x>", this page keeps
  // "PPC <x>" and "pay-per-click <x>", and neither list carries the other's phrasing.
  'ppc-agency-montreal.html': [
    'PPC agency Montreal', 'PPC management Montreal', 'PPC agency',
    'PPC management services', 'pay-per-click agency Montreal', 'PPC campaign management',
    'PPC optimization', 'PPC audit', 'paid search management Montreal',
    'bilingual PPC campaigns Montreal',
  ],
  // The DENTAL audience page. Every term carries dental/dentist — do NOT add plain
  // 'Google Ads management' or 'dental SEO' here (that is seo.html's).
  'google-ads-for-dentists.html': [
    'Google Ads for dentists', 'dental Google Ads agency', 'Google Ads for dental practices',
    'dental PPC agency', 'dentist PPC', 'dental practice advertising',
    'dental implant Google Ads', 'Invisalign Google Ads', 'emergency dentist ads',
    'dental marketing agency Montreal',
  ],
  // The LEGAL audience page. Same rule: every term carries law firm / lawyer /
  // attorney / legal.
  'google-ads-for-law-firms.html': [
    'Google Ads for law firms', 'legal PPC management', 'law firm PPC agency',
    'Google Ads for lawyers', 'attorney PPC', 'law firm Google Ads management',
    'personal injury lawyer ads', 'legal advertising agency', 'lawyer PPC campaigns',
    'law firm marketing agency Montreal',
  ],
  // The SMALL BUSINESS audience page. 'small business PPC' is fine alongside
  // ppc-agency-montreal.html's 'PPC agency' — one is an audience modifier, the other
  // a geo one, and they return different SERPs.
  'google-ads-for-small-business.html': [
    'Google Ads for small business', 'small business Google Ads', 'small business PPC',
    'Google Ads small budget', 'Google Ads for local business', 'local Google Ads',
    'small business PPC management', 'small business advertising agency',
    'affordable Google Ads management',
  ],
  // Email is split from Klaviyo the same way paid ads is (see google-ads.html):
  // email.html owns the PLATFORM-NEUTRAL email terms, klaviyo.html owns every
  // Klaviyo term. Do not put "Klaviyo agency" back here — two of our own pages
  // chasing one query is how you split your own ranking signal.
  'email.html': [
    'email marketing agency Montreal', 'email marketing agency', 'email marketing Montreal',
    'email marketing automation', 'lifecycle marketing', 'email flows',
    'list segmentation', 'lead nurturing', 'retention marketing',
    'HubSpot email marketing',
  ],
  'klaviyo.html': [
    'Klaviyo Partner Agency Montreal', 'Klaviyo agency Montreal', 'Klaviyo agency',
    'Klaviyo email marketing', 'Klaviyo SMS marketing', 'Klaviyo flows',
    'Klaviyo automation', 'Klaviyo migration', 'ecommerce email marketing agency',
    'Shopify Klaviyo agency', 'bilingual email marketing Montreal',
  ],
  'ai-seo.html': [
    'AI SEO services', 'generative engine optimization', 'GEO agency',
    'ChatGPT SEO', 'Perplexity optimization', 'Google AI Overviews',
    'AI search visibility', 'answer engine optimization',
  ],
  'ai-seo-agency.html': [
    'AI SEO agency', 'AI SEO company', 'generative engine optimization agency',
    'AI search agency', 'ChatGPT optimization agency', 'LLM SEO agency',
    'answer engine optimization agency', 'hire AI SEO agency',
  ],
  'ai-seo-montreal.html': [
    'AI SEO Montreal', 'AI SEO agency Montreal', 'generative engine optimization Montreal',
    'GEO agency Montreal', 'ChatGPT SEO Montreal', 'AI search optimization Montreal',
    'Montreal SEO agency', 'bilingual AI SEO', 'Google AI Overviews Montreal',
  ],
  'etf-marketing.html': [
    'ETF marketing agency', 'ETF marketing services', 'asset manager marketing',
    'ETF distribution', 'ETF launch marketing', 'financial advisor targeting',
    'fund marketing', 'AUM growth',
  ],
  // The startup AUDIENCE page. Fenced off from seo.html the same way ecommerce.html
  // is fenced off from shopify-seo.html: seo.html owns the generic head terms
  // ('search engine optimization', 'SEO agency Montreal', 'technical SEO services'),
  // and this page owns only the terms that carry the word startup / SaaS. Do NOT add
  // 'SEO agency' or 'technical SEO' here — two of our own pages chasing one query is
  // how you split your own ranking signal. 'AI startup SEO' is the audience (startups
  // that build AI), NOT ai-seo.html's generative-engine terms; keep those out too.
  'startup-seo.html': [
    'SEO agency for startups', 'startup SEO agency', 'startup SEO services',
    'SEO for startups', 'startup SEO', 'SaaS SEO agency', 'B2B SaaS SEO',
    'AI startup SEO', 'early stage startup SEO', 'organic growth for startups',
  ],
  // The /ecommerce PILLAR. It is the hub ABOVE shopify / shopify-seo / klaviyo /
  // google-ads / meta-ads, so its terms are deliberately the UMBRELLA ones only.
  // Do NOT add 'ecommerce SEO agency' or 'ecommerce SEO services' here — those are
  // in shopify-seo.html's list AND in its <title>; and 'ecommerce email marketing
  // agency' is klaviyo.html's. A hub that chases its own spokes' queries is just a
  // slower way to split one ranking signal. What this page owns instead is the
  // agency-level head terms plus WooCommerce/Magento, which no page targeted before
  // (shopify.html mentions them only as migration sources).
  'ecommerce.html': [
    'ecommerce agency Montreal', 'ecommerce agency', 'ecommerce marketing agency',
    'ecommerce development agency', 'ecommerce web design Montreal',
    'WooCommerce agency Montreal', 'Magento agency', 'ecommerce migration',
    'online store agency Montreal', 'bilingual ecommerce agency',
  ],
  // Retargeted 2026-07-27 off AEO and back onto ChatGPT Ads, which is what
  // services.html row 06 and the /ads overview have always called this page.
  // The AEO/GEO/answer-engine terms are ai-seo.html's; do not put them back here.
  'chatgpt-ads.html': [
    'ChatGPT Ads agency Montreal', 'ChatGPT Ads agency', 'ChatGPT advertising',
    'AI advertising agency Montreal', 'AI advertising services', 'AI ads Montreal',
    'conversational AI advertising', 'OpenAI advertising', 'AI ad creative',
    'AI landing page optimization', 'AI campaign management', 'bilingual AI advertising Montreal',
  ],
  'software.html': [
    'custom software development', 'CRM development services', 'custom CRM',
    'business dashboards', 'software integration', 'marketing automation software',
    'internal tools development',
  ],
  // Shopify is split across two pages the same way paid ads is (see google-ads.html):
  // shopify.html owns the BUILD terms, shopify-seo.html owns the SEARCH terms. Do not
  // put "Shopify SEO" back here — two of our own pages chasing one query is how you
  // split your own ranking signal.
  'shopify.html': [
    'Shopify development agency', 'Shopify store design', 'Shopify Plus development',
    'Shopify theme development', 'headless Shopify', 'Shopify migration',
    'ecommerce conversion optimization', 'custom Shopify theme', 'Shopify developer Montreal',
  ],
  'shopify-seo.html': [
    'Shopify SEO agency Montreal', 'Shopify SEO agency', 'Shopify SEO services',
    'Shopify SEO', 'ecommerce SEO agency', 'ecommerce SEO services',
    'Shopify technical SEO', 'Shopify store optimization', 'Shopify migration SEO',
    'bilingual Shopify SEO',
  ],
  'ads.html': [
    'paid advertising agency', 'ad management agency', 'Reddit ads agency',
    'Pinterest ads agency', 'Amazon ads agency', 'Spotify ads agency',
    'paid media agency Montreal', 'performance advertising',
  ],
  // The Reddit and Pinterest hubs are the ONLY two ad hubs whose Montreal city page
  // still exists (amazon/spotify/meta/chatgpt Montreal were retired into their hubs).
  // So, unlike those, these two hubs must NOT chase "<platform> ads Montreal" — the
  // city page owns that query. Leaving it here is what made /ads/reddit-ads and
  // /reddit-ads-montreal ship the SAME <title>, i.e. two of our own pages splitting
  // one ranking signal. Keep the hub terms platform-level and vertical-level.
  'reddit-ads.html': [
    'Reddit ads agency', 'Reddit ads management', 'Reddit advertising',
    'Promoted Posts', 'subreddit targeting', 'Reddit PPC',
    'Reddit conversation ads', 'B2B Reddit advertising', 'community advertising',
  ],
  'pinterest-ads.html': [
    'Pinterest ads agency', 'Pinterest ads management', 'Pinterest advertising',
    'Pinterest shopping ads', 'promoted pins', 'Pinterest ecommerce ads',
    'Pinterest catalog ads', 'visual discovery advertising',
  ],
  'amazon-ads.html': [
    'Amazon ads agency Montreal', 'Amazon ads agency', 'Amazon PPC agency',
    'Amazon advertising management', 'Sponsored Products', 'Sponsored Brands',
    'Amazon DSP', 'Amazon listing optimization', 'ACOS optimization', 'amazon.ca sellers',
  ],
  'spotify-ads.html': [
    'Spotify ads agency', 'Spotify advertising', 'audio ads agency',
    'podcast advertising', 'Spotify Ad Studio', 'streaming audio ads',
    'Spotify ads Montreal', 'audio branding',
  ],
  'book-call.html': [
    'book a strategy call', 'marketing consultation', 'growth strategy call',
    'free marketing audit', 'Davnoot contact',
  ],
  // ---- Location landing pages: 6 ad platforms × Montreal / Ottawa / Toronto ----
  // Flat root pages (e.g. /reddit-ads-montreal), landing type (Organization + FAQPage).
  'reddit-ads-montreal.html': [
    'Reddit ads Montreal', 'Reddit ads agency Montreal', 'Reddit advertising Montreal',
    'r/montreal ads', 'subreddit targeting Montreal', 'Reddit PPC Montreal',
    'bilingual Reddit ads', 'community advertising Montreal',
  ],
  'reddit-ads-ottawa.html': [
    'Reddit ads Ottawa', 'Reddit ads agency Ottawa', 'Reddit advertising Ottawa',
    'r/ottawa ads', 'subreddit targeting Ottawa', 'Reddit PPC Ottawa',
    'B2B Reddit ads Ottawa', 'community advertising Ottawa',
  ],
  'reddit-ads-toronto.html': [
    'Reddit ads Toronto', 'Reddit ads agency Toronto', 'Reddit advertising Toronto',
    'r/toronto ads', 'subreddit targeting Toronto', 'Reddit PPC Toronto',
    'GTA Reddit ads', 'community advertising Toronto',
  ],
  'pinterest-ads-montreal.html': [
    'Pinterest ads Montreal', 'Pinterest ads agency Montreal', 'Pinterest advertising Montreal',
    'Pinterest shopping ads Montreal', 'promoted pins Montreal', 'bilingual Pinterest ads',
    'Pinterest ecommerce Montreal', 'visual discovery Montreal',
  ],
  'pinterest-ads-ottawa.html': [
    'Pinterest ads Ottawa', 'Pinterest ads agency Ottawa', 'Pinterest advertising Ottawa',
    'Pinterest shopping ads Ottawa', 'promoted pins Ottawa', 'Pinterest wedding ads Ottawa',
    'Pinterest ecommerce Ottawa', 'visual discovery Ottawa',
  ],
  'pinterest-ads-toronto.html': [
    'Pinterest ads Toronto', 'Pinterest ads agency Toronto', 'Pinterest advertising Toronto',
    'Pinterest shopping ads Toronto', 'promoted pins Toronto', 'GTA Pinterest ads',
    'Pinterest ecommerce Toronto', 'visual discovery Toronto',
  ],
  // No amazon-ads-montreal entry: that page was retired (301 -> /ads/amazon-ads),
  // which now targets "Amazon ads agency Montreal" in its own title and H1. Two of
  // our own pages chasing one query is how you split your own ranking signal.
  'amazon-ads-ottawa.html': [
    'Amazon ads Ottawa', 'Amazon PPC agency Ottawa', 'Amazon advertising Ottawa',
    'Sponsored Products Ottawa', 'Amazon seller Ottawa', 'Amazon DSP Ottawa',
    'ACOS optimization Ottawa', 'amazon.ca Ottawa',
  ],
  'amazon-ads-toronto.html': [
    'Amazon ads Toronto', 'Amazon PPC agency Toronto', 'Amazon advertising Toronto',
    'Sponsored Products Toronto', 'Amazon seller Toronto', 'GTA Amazon sellers',
    'ACOS optimization Toronto', 'Amazon DSP Toronto',
  ],
  // No spotify-ads-montreal entry: that page was retired (301 -> /ads/spotify-ads),
  // which already targets "Spotify ads agency Montreal" in its own title. Two of our
  // own pages chasing one query is how you split your own ranking signal.
  'spotify-ads-ottawa.html': [
    'Spotify ads Ottawa', 'audio ads Ottawa', 'Spotify advertising Ottawa',
    'podcast advertising Ottawa', 'Spotify Ad Studio Ottawa', 'bilingual audio ads Ottawa',
    'streaming audio ads Ottawa', 'audio branding Ottawa',
  ],
  'spotify-ads-toronto.html': [
    'Spotify ads Toronto', 'audio ads Toronto', 'Spotify advertising Toronto',
    'podcast advertising Toronto', 'Spotify Ad Studio Toronto', 'GTA audio ads',
    'streaming audio ads Toronto', 'audio branding Toronto',
  ],
  // The Meta city pages target paid SOCIAL terms only. "Google Ads <city>" belongs to
  // google-ads.html, which targets it in its own title — two of our own pages chasing
  // one query is how you split your own ranking signal.
  // No meta-ads-montreal entry: that page was retired (301 -> /services/meta-ads),
  // which now targets "Meta Ads Agency Montreal" in its own title and H1. Two of our
  // own pages chasing one query is how you split your own ranking signal.
  'meta-ads-ottawa.html': [
    'Meta ads Ottawa', 'Facebook ads Ottawa', 'Instagram ads Ottawa',
    'paid social Ottawa', 'Meta ads agency Ottawa', 'B2B paid social Ottawa',
    'bilingual ad campaigns Ottawa', 'performance marketing Ottawa',
  ],
  'meta-ads-toronto.html': [
    'Meta ads Toronto', 'Facebook ads Toronto', 'Instagram ads Toronto',
    'paid social Toronto', 'Meta ads agency Toronto', 'GTA paid social',
    'Reels ads Toronto', 'performance marketing Toronto',
  ],
  // No chatgpt-ads-montreal entry: there is no such page. The file was never on
  // disk, but the routing, this keyword list, and three internal links all pointed
  // at it, so /chatgpt-ads-montreal served a hard 404 to every visitor and crawler
  // that followed one. It is now retired the same way as the other Montreal city
  // pages (301 -> /services/chatgpt-ads), which already targets "ChatGPT Ads Agency
  // Montreal" in its own title and H1.
  'chatgpt-ads-ottawa.html': [
    'ChatGPT ads Ottawa', 'AI search advertising Ottawa', 'Perplexity ads Ottawa',
    'AI ads agency Ottawa', 'generative AI ads Ottawa', 'B2B AI ads Ottawa',
    'sponsored AI answers Ottawa', 'AI advertising Ottawa',
  ],
  'chatgpt-ads-toronto.html': [
    'ChatGPT ads Toronto', 'AI search advertising Toronto', 'Perplexity ads Toronto',
    'AI ads agency Toronto', 'generative AI ads Toronto', 'GTA AI ads',
    'sponsored AI answers Toronto', 'AI advertising Toronto',
  ],
};

/* ---- French keywords -------------------------------------------------------
 * NOT a translation of KEYWORDS above, and the difference is the whole point.
 * "SEO agency Montreal" translated word-for-word is "agence SEO Montréal", but the
 * term Quebecers actually search is "référencement naturel" / "agence de
 * référencement" — different queries, different volumes. Running the English list
 * through a translator would target phrases nobody types.
 *
 * Both spellings of the head terms are kept where the market genuinely splits
 * (Quebec uses "SEO" and "référencement" interchangeably in the trade), and
 * "Montréal" is accented — that is how it is typed in French.
 *
 * A page with no entry here emits no keywords tag, exactly like the English map.
 */
export const KEYWORDS_FR = {
  'index.html': [
    'agence de marketing numérique Montréal', 'agence de croissance Montréal',
    'agence de référencement', 'publicité sur les réseaux sociaux',
    'marketing par courriel', 'optimisation pour la recherche IA',
    'publicités ChatGPT', 'développement de logiciels sur mesure', 'marketing de revenu',
  ],
  'seo.html': [
    'agence de référencement Montréal', 'agence SEO Montréal', 'référencement naturel Montréal',
    'audit SEO', 'référencement technique', 'stratégie de mots-clés',
    'optimisation on-page', 'création de liens', 'croissance du trafic organique',
  ],
  'meta-ads.html': [
    'agence Meta Ads Montréal', 'agence publicité Facebook Montréal',
    'gestion de publicités Facebook', 'publicité Instagram Montréal',
    'publicité sur les réseaux sociaux Montréal', 'campagnes Advantage+',
    'test créatif', 'campagnes publicitaires bilingues Montréal', 'marketing de performance Montréal',
  ],
  'email.html': [
    'agence de marketing par courriel Montréal', 'marketing par courriel Montréal',
    'automatisation du marketing par courriel', 'marketing du cycle de vie',
    'séquences de courriels', 'segmentation de listes', 'nurturing de prospects',
    'marketing de rétention', 'infolettre',
  ],
  'ai-seo.html': [
    'référencement IA', 'optimisation pour moteurs génératifs', 'agence GEO',
    'référencement ChatGPT', 'optimisation Perplexity', 'aperçus IA de Google',
    'visibilité dans la recherche IA', 'optimisation pour moteurs de réponse',
  ],
  'chatgpt-ads.html': [
    'agence publicités ChatGPT Montréal', 'publicité ChatGPT', 'agence de publicité IA Montréal',
    'publicité par intelligence artificielle', 'publicités IA Montréal',
    'publicité conversationnelle IA', 'publicité OpenAI', 'création publicitaire IA',
    'publicité IA bilingue Montréal',
  ],
  'software.html': [
    'développement de logiciels sur mesure', 'développement CRM sur mesure', 'CRM personnalisé',
    'tableaux de bord d\'affaires', 'intégration de systèmes',
    'logiciel d\'automatisation marketing', 'développement d\'outils internes', 'développeur Montréal',
  ],
  'book-call.html': [
    'réserver un appel stratégique', 'consultation en marketing', 'appel de stratégie de croissance',
    'audit marketing gratuit', 'contacter Davnoot',
  ],
  // Quebec keeps the English "startup" (and "SaaS") in the trade — "jeune pousse"
  // is France French and nobody here types it — but the SERVICE word is
  // "référencement", so both spellings of the head term are carried. Note this is
  // NOT a translation of the English list: "SEO for startups" word-for-word would
  // be "SEO pour startups", which is a real query, but the higher-volume Quebec
  // phrasing is "référencement pour startups" and that is what leads here.
  'startup-seo.html': [
    'agence SEO pour startups', 'référencement pour startups', 'agence de référencement startup',
    'SEO startup', 'référencement SaaS', 'agence SEO SaaS',
    'marketing web pour startups', 'référencement jeune entreprise',
    'visibilité organique startup', 'croissance organique startup',
  ],
  /* The Google Ads / PPC cluster. Quebec keeps "Google Ads" and "PPC" as-is (nobody
   * types "publicité au coût par clic" into a search box), but the SERVICE words are
   * French — "agence", "gestion", "campagnes publicitaires" — and the audience words
   * always are: "dentistes", "avocats", "PME". "PME" specifically is the Quebec term
   * for a small business; a literal "petite entreprise" is understood but "PME" is
   * what gets searched. */
  'ppc-agency-montreal.html': [
    'agence PPC Montréal', 'gestion de campagnes PPC', 'agence de publicité Google Montréal',
    'gestion de publicité payante', 'campagnes au coût par clic', 'optimisation PPC',
    'audit de compte publicitaire', 'agence de référencement payant Montréal',
    'publicité payante Montréal', 'gestion de budget publicitaire',
  ],
  'google-ads-for-dentists.html': [
    'Google Ads pour dentistes', 'publicité Google pour cliniques dentaires',
    'agence marketing dentaire Montréal', 'publicité implants dentaires',
    'marketing pour cabinet dentaire', 'campagnes Google Ads dentiste',
    'publicité Invisalign', 'acquisition de patients en ligne',
    'publicité dentiste urgence', 'agence publicitaire dentaire',
  ],
  'google-ads-for-law-firms.html': [
    'Google Ads pour avocats', 'publicité Google cabinet d\'avocats',
    'marketing juridique Montréal', 'agence publicitaire pour avocats',
    'campagnes PPC juridiques', 'publicité pour cabinet juridique',
    'acquisition de clients avocat', 'publicité droit de la famille',
    'marketing pour notaires et avocats', 'agence marketing juridique',
  ],
  'google-ads-for-small-business.html': [
    'Google Ads pour PME', 'publicité Google petite entreprise',
    'campagnes publicitaires PME', 'publicité en ligne pour PME Québec',
    'petit budget publicitaire Google', 'agence publicitaire pour PME Montréal',
    'publicité locale Google', 'marketing numérique pour PME',
    'annonces Google commerce local', 'rentabilité publicitaire PME',
  ],
};

// Business contact / local-SEO details (used for LocalBusiness + Organization schema).
export const PHONE = '+1-438-223-7131';

// ---- Helpers ---------------------------------------------------------------
export const esc = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// Turn an HTML fragment into clean plain text (for JSON-LD answer bodies):
// strip inline tags, decode the handful of entities we actually use, collapse whitespace.
export const toPlainText = (s) =>
  String(s)
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#0?39;|&apos;|&#x27;/gi, "'")
    .replace(/\s+/g, ' ')
    .trim();

// Public URLs are EXTENSIONLESS: /seo, not /seo.html (home is /). vercel.json
// 301-redirects every /<name>.html to its clean path and serves the static file
// at the clean URL, so this is the one canonical form Google sees. `pathFor()` in
// scripts/compile-pages.js keeps the DB overlay key as /<name>.html (an internal
// join key the admin CMS writes) — that is deliberately NOT the public URL.
export function cleanPath(file, locale = DEFAULT_LOCALE) {
  const pre = localePrefix(locale);
  // The French home is /fr, not /fr/ — a trailing slash here would fight
  // vercel.json's `trailingSlash: false` and 308 on every single visit.
  if (file === 'index.html') return pre || '/';
  const name = file.replace(/\.html$/, '');
  // The 7-service pages live under /services/* (e.g. /services/seo). Everything
  // else (book-call, privacy, the two AI-SEO landing pages, the /services index)
  // stays at the top level. The DB overlay key (pathFor in compile-pages.js) is
  // deliberately still /seo.html — public URL ≠ storage key.
  // ADS_PAGES live one level down at /ads/<name> (e.g. /ads/reddit-ads); the
  // 7-service pages at /services/<name>; everything else (book-call, privacy, the
  // /services and /ads overview indexes, the landing pages) stays top-level.
  return pre + (SERVICE_PAGES.includes(file) ? '/services/' : ADS_PAGES.includes(file) ? '/ads/' : '/') + name;
}
export function canonicalFor(file, locale = DEFAULT_LOCALE) {
  return SITE_URL + cleanPath(file, locale);
}

/**
 * The href a link to `file` should use when rendering in `locale` — the French URL
 * if that page is translated, the English one if it is not.
 *
 * Linking a French visitor to an English page is a compromise; linking them to a
 * /fr URL that 404s is a bug. Until TRANSLATED_PAGES covers the whole site, the
 * compromise is the correct behaviour, and it disappears page by page on its own.
 */
export function hrefFor(file, locale = DEFAULT_LOCALE) {
  return cleanPath(file, hasTranslation(file, locale) ? locale : DEFAULT_LOCALE);
}

/**
 * Serialize a JSON-LD graph for embedding inside <script type="application/ld+json">.
 *
 * The `<` escaping is NOT cosmetic. JSON.stringify happily emits a literal
 * `</script>` if one appears in any string — a post titled `Why </script> tags
 * break SEO` would CLOSE the JSON-LD block early and inject the remainder of the
 * title into the document as live HTML. Escaping `<` to < is still valid
 * JSON, parses identically, and makes the breakout impossible.
 *
 * Use this everywhere instead of a bare JSON.stringify into a <script> tag.
 */
export function jsonLdSafe(graph) {
  return JSON.stringify(graph, null, 2).replace(/</g, '\\u003c');
}

// ---- Chrome ----------------------------------------------------------------
export function navHtml(file, base = '', settings = SITE_DEFAULTS, locale = DEFAULT_LOCALE) {
  const brand = (settings || SITE_DEFAULTS).brand || {};
  const logo = brand.logo || LOGO;
  const wordmark = brand.wordmark || 'Davnoot Digital';
  const isHome = file === 'index.html';
  const pre = localePrefix(locale);
  // Anchor prefix: "#services" on home, "/#services" elsewhere — and "/fr#services"
  // in French, so an in-page anchor from a French page never bounces to the English home.
  const home = isHome ? '' : pre || '/';
  let active = '';
  if (file === 'book-call.html') active = 'contact';
  else if (file === 'blog') active = 'blog';
  else if (file === 'ads.html' || ADS_PAGES.includes(file)) active = 'ads';
  else if (file === 'services.html' || SERVICE_PAGES.includes(file) || FLAT_SERVICE_PAGES.includes(file)) active = 'services';
  const act = (n) => (active === n ? ' class="active"' : '');
  const ctaHref = file === 'book-call.html' ? '#form' : hrefFor('book-call.html', locale);
  const ctaText = file === 'book-call.html' ? t(locale, 'jumpForm') : t(locale, 'bookCall');
  const lang = localeSwitcherHtml(file, locale);
  return `<nav>
  <a href="${pre || '/'}" class="logo" data-cursor>
    <img src="/${logo}" alt="${esc(brand.name || 'Davnoot')}" class="logo-mark" />
    <span class="wordmark">${wordmark}</span>
  </a>
  <ul class="nav-links">
    <li><a href="${hrefFor('services.html', locale)}"${act('services')} data-cursor>${t(locale, 'services')}</a></li>
    <li><a href="${hrefFor('ads.html', locale)}"${act('ads')} data-cursor>${t(locale, 'ads')}</a></li>
    <li><a href="${home}#process" data-cursor>${t(locale, 'process')}</a></li>
    <li><a href="${home}#results" data-cursor>${t(locale, 'work')}</a></li>
    <li><a href="/blog"${act('blog')} data-cursor>${t(locale, 'blog')}</a></li>
    <li><a href="${hrefFor('book-call.html', locale)}"${act('contact')} data-cursor>${t(locale, 'contact')}</a></li>
${lang}  </ul>
  <a href="${ctaHref}" class="nav-cta" data-cursor>${ctaText}</a>
  <button class="nav-toggle" type="button" aria-label="${t(locale, 'toggleMenu')}" aria-expanded="false"><span></span><span></span><span></span></button>
</nav>`;
}

/**
 * The EN|FR switcher.
 *
 * It links to the SAME page in the other language — the single most common
 * execution failure in bilingual sites is a switcher that dumps everyone on the
 * translated homepage, which trains people never to touch it again.
 *
 * RENDERED ONLY WHERE BOTH VERSIONS EXIST. A page with no French counterpart
 * shows no toggle at all, rather than a toggle that silently means "go to the
 * French homepage and find your own way back" — which is the same failure as
 * above wearing a different hat. Because TRANSLATED_PAGES is measured from actual
 * coverage, a page grows its toggle, in both languages at once, on the build
 * after its translation is finished.
 *
 * `hreflang`+`lang` on the anchor tell a screen reader to pronounce the label in
 * the target language, and tell a crawler what is on the other end of the link.
 *
 * The visible label is the two-letter code, not the language name. Partly it is
 * the convention, but concretely: "English" is 7 characters in a nav bar that has
 * to fit six French labels which are already ~20% longer than their English
 * counterparts, and the horizontal nav has to survive down to 1001px before the
 * burger takes over at 1000px. The full phrase lives in `title`/`aria-label`,
 * where it costs no width and still reaches a screen reader.
 *
 * Emitted in BOTH directions: French pages link back to English, and the English
 * pages that have a French twin advertise it. Without the English half, /fr is
 * reachable only by typing the URL or arriving from Google — the French site
 * exists but nobody browsing the English one can find it.
 */
export function localeSwitcherHtml(file, locale = DEFAULT_LOCALE) {
  if (!TRANSLATED_PAGES.has(file)) return '';
  const other = otherLocale(locale);
  const href = cleanPath(file, other);
  const label = esc(t(locale, 'switchLabel'));
  return `    <li class="nav-lang"><a href="${href}" hreflang="${other}" lang="${other}" title="${label}" aria-label="${label}" data-cursor>${t(locale, 'switchTo')}</a></li>\n`;
}

export function footerHtml(file, base = '', settings = SITE_DEFAULTS, locale = DEFAULT_LOCALE) {
  const s = settings || SITE_DEFAULTS;
  const brand = s.brand || {};
  const contact = s.contact || {};
  const logo = brand.logo || LOGO;
  const wordmark = brand.wordmark || 'Davnoot Digital';
  const email = contact.email || 'info@davnoot.com';
  const phoneHref = (contact.phone || PHONE).replace(/[^\d+]/g, '');
  const phoneDisplay = contact.phoneDisplay || '+1 (438) 223-7131';
  const pre = localePrefix(locale);
  const home = file === 'index.html' ? '' : pre || '/'; // anchor prefix, as in navHtml
  const href = (f) => hrefFor(f, locale);
  const T = (k) => t(locale, k);
  // The footer's social links and the Organization schema's sameAs are the same
  // list of profiles, so they read from one place: org.sameAs in the settings.
  // Matched by host, not by position, so reordering sameAs cannot swap the labels.
  const sameAs = Array.isArray(s.org?.sameAs) ? s.org.sameAs : [];
  const profile = (host, fallback) => esc(sameAs.find((u) => u.includes(host)) || fallback);
  const linkedin = profile('linkedin.com', 'https://www.linkedin.com/company/davnoot/');
  const instagram = profile('instagram.com', 'https://www.instagram.com/davnootdigital/');
  return `<footer id="contact">
  <div class="footer-top">
    <div>
      <a href="${pre || '/'}" class="logo" data-cursor>
        <img src="/${logo}" alt="${esc(brand.name || 'Davnoot')}" class="logo-mark footer-logo-mark" />
        <span class="wordmark">${wordmark}</span>
      </a>
      <p class="footer-tagline">${T('tagline')}</p>
    </div>
    <div class="footer-col">
      <h4>${T('colServices')}</h4>
      <ul>
        <li><a href="${href('ecommerce.html')}" data-cursor>${T('ecommerce')}</a></li>
        <li><a href="${href('ads.html')}" data-cursor>${T('adPlatforms')}</a></li>
        <li><a href="${href('seo.html')}" data-cursor>${T('seo')}</a></li>
        <li><a href="${href('google-ads.html')}" data-cursor>${T('googleAds')}</a></li>
        <li><a href="${href('meta-ads.html')}" data-cursor>${T('metaAds')}</a></li>
        <li><a href="${href('email.html')}" data-cursor>${T('email')}</a></li>
        <li><a href="${href('ai-seo.html')}" data-cursor>${T('aiSeo')}</a></li>
        <li><a href="${href('chatgpt-ads.html')}" data-cursor>${T('chatgptAds')}</a></li>
        <li><a href="${href('software.html')}" data-cursor>${T('software')}</a></li>
        <li><a href="${href('shopify.html')}" data-cursor>${T('shopify')}</a></li>
        <li><a href="${href('shopify-seo.html')}" data-cursor>${T('shopifySeo')}</a></li>
        <li><a href="${href('klaviyo.html')}" data-cursor>${T('klaviyo')}</a></li>
      </ul>
    </div>
    <div class="footer-col">
      <h4>${T('colCompany')}</h4>
      <ul>
        <li><a href="${home}#about" data-cursor>${T('about')}</a></li>
        <li><a href="${home}#results" data-cursor>${T('work')}</a></li>
        <li><a href="${home}#process" data-cursor>${T('process')}</a></li>
        <li><a href="/blog" data-cursor>${T('blog')}</a></li>
      </ul>
      ${/* THE ORPHAN FIX. These three pages were in sitemap.xml and reachable by
           nobody: not one page on the site linked to them, so a crawler that
           follows links never saw them (Semrush 2026-08-01: "Orphaned sitemap
           pages"). A URL you submit but never link is a URL you are telling Google
           you don't believe in. They live here because the footer is the only
           surface every page shares — do not move them into a body section on one
           page and call it done. /privacy is the fourth, in .footer-bottom below. */ ''}
      <h4>${T('colSpecialties')}</h4>
      <ul>
        <li><a href="${href('startup-seo.html')}" data-cursor>${T('startupSeo')}</a></li>
        <li><a href="${href('ppc-agency-montreal.html')}" data-cursor>${T('ppcMontreal')}</a></li>
        <li><a href="${href('google-ads-for-small-business.html')}" data-cursor>${T('smallBizAds')}</a></li>
        <li><a href="${href('google-ads-for-dentists.html')}" data-cursor>${T('dentalAds')}</a></li>
        <li><a href="${href('google-ads-for-law-firms.html')}" data-cursor>${T('legalAds')}</a></li>
        <li><a href="${href('ai-seo-agency.html')}" data-cursor>${T('aiSeoAgency')}</a></li>
        <li><a href="${href('ai-seo-montreal.html')}" data-cursor>${T('aiSeoMontreal')}</a></li>
        <li><a href="${href('etf-marketing.html')}" data-cursor>${T('etf')}</a></li>
      </ul>
    </div>
    <div class="footer-col">
      <h4>${T('colContact')}</h4>
      <ul>
        <li><a href="mailto:${email}" data-cursor>${email}</a></li>
        <li><a href="tel:${phoneHref}" data-cursor>${phoneDisplay}</a></li>
        <li><a href="${linkedin}" target="_blank" rel="noopener" data-cursor>LinkedIn ↗</a></li>
        <li><a href="${instagram}" target="_blank" rel="noopener" data-cursor>Instagram ↗</a></li>
      </ul>
    </div>
  </div>

  <div class="footer-big">Davnoot<em>.</em></div>

  <div class="footer-bottom">
    <span>${T('rights')}</span>
    <a href="${href('privacy.html')}" data-cursor>${T('privacy')}</a>
    <span>${T('builtIn')}</span>
  </div>
</footer>`;
}

// ---- Structured data -------------------------------------------------------
// The Organization node is referenced by @id from every other node (including
// BlogPosting's publisher), so it must stay stable.
//
// SETTINGS-DRIVEN, byte-identically at defaults. Every field reads from the merged
// site settings (SITE_DEFAULTS + the db.settings diff), and each default value in
// SITE_DEFAULTS mirrors the constant it replaced — so orgNode() === orgNode(defaults)
// to the byte (asserted in scripts/settings-render.test.js and, end-to-end, by the
// golden test, since build.js bakes this node into every page's JSON-LD). A brand /
// contact / org edit in /admin therefore flows into the Organization schema anywhere
// orgNode is regenerated from live settings (the blog today; the marketing pages once
// their <head> JSON-LD is modelled as a hole — see the settings→render note in TODO).
export function orgNode(settings = SITE_DEFAULTS) {
  const s = settings || SITE_DEFAULTS;
  const brand = s.brand || {};
  const contact = s.contact || {};
  const org = s.org || {};
  const addr = contact.address || {};
  const siteUrl = s.defaults?.siteUrl || SITE_URL;
  const ogImage = s.defaults?.ogImage || OG_IMAGE;
  return {
    '@type': 'Organization',
    '@id': siteUrl + '/#organization',
    name: brand.name || 'Davnoot',
    url: siteUrl + '/',
    logo: ogImage,
    image: ogImage,
    description: org.description || ORG_DESC,
    email: contact.email || 'info@davnoot.com',
    telephone: contact.phone || PHONE,
    foundingDate: org.foundingDate || '2025',
    address: { '@type': 'PostalAddress', addressLocality: addr.locality || 'Montreal', addressRegion: addr.region || 'QC', addressCountry: addr.country || 'CA' },
    areaServed: 'Worldwide',
    ...(org.sameAs?.length ? { sameAs: org.sameAs } : {}),
  };
}

/** The content type of a marketing FILE, for the structured-data registry. */
export function schemaTypeFor(file) {
  if (file === 'index.html') return 'home';
  if (file === 'book-call.html') return 'contact';
  if (SERVICE_PAGES.includes(file)) return 'service';
  if (ADS_PAGES.includes(file)) return 'service'; // ad hubs emit Service + FAQPage, like /services/* (serviceType from SERVICE_TYPE)
  if (FLAT_SERVICE_PAGES.includes(file)) return 'service'; // a service page that just happens to live at a flat URL
  return 'landing';
}

/**
 * The marketing-page JSON-LD. This is now a thin adapter over the single site-wide
 * builder in lib/structured-data.js — there is no second, hand-written graph here to
 * drift from the blog's. The node set and order come from CONFIG[type].nodes; this
 * function only picks the type and wraps the result.
 *
 * Proven byte-identical to the previous inline builder by scripts/pages-golden.test.js
 * (the compiled BUILD:SEO region is a pure function of this output, so any drift fails
 * `npm run site`) and by scripts/structured-data.test.js.
 */
export function jsonLd(file, title, desc, faqs, locale = DEFAULT_LOCALE) {
  const graph = buildGraph({ file, title, desc, faqs }, canonicalFor(file, locale), schemaTypeFor(file));
  return jsonLdSafe({ '@context': 'https://schema.org', '@graph': graph });
}

/**
 * The hreflang cluster for a page that exists in both languages.
 *
 * Emitted on BOTH sides and pointing at BOTH URLs including itself — that
 * reciprocity is not optional. Google ignores a one-way annotation entirely, and
 * an unannotated pair of near-identical pages is exactly what it treats as
 * duplicate content, which is the failure mode this whole feature exists to avoid.
 *
 * LANGUAGE GRANULARITY IS DELIBERATELY ASYMMETRIC:
 *   en      — not en-CA. The Organization schema says areaServed "Worldwide"; the
 *             English pages rank for US and global queries today, and pinning them
 *             to Canada would tell Google to prefer them only for Canadian users.
 *   fr-CA   — the French pages ARE for Quebec. Quebec French is not France French
 *             (the copy says "courriel" and "magasinage"), so claiming plain "fr"
 *             would invite Google to serve them to France, where they read oddly.
 *   x-default — English, the entry point for anyone we have no better match for.
 */
export function hreflangTags(file) {
  if (!TRANSLATED_PAGES.has(file)) return [];
  const en = canonicalFor(file, 'en');
  const fr = canonicalFor(file, 'fr');
  return [
    `<link rel="alternate" hreflang="en" href="${en}" />`,
    `<link rel="alternate" hreflang="fr-CA" href="${fr}" />`,
    `<link rel="alternate" hreflang="x-default" href="${en}" />`,
  ];
}

export function seoHtml(file, title, desc, faqs, locale = DEFAULT_LOCALE) {
  const canonical = canonicalFor(file, locale);
  // A French page canonicalises to ITSELF. Pointing it at the English URL — the
  // reflex when you think of French as "a version of" the real page — would ask
  // Google to drop it from the index, and no amount of hreflang would bring it back.
  const kw = locale === 'fr' ? KEYWORDS_FR[file] : KEYWORDS[file];
  /* A French page whose dictionary is not finished is still ROUTED — so it can be
   * reviewed in a browser before it goes live — but it must not be indexable. It
   * is mostly the English page at that point, and letting Google have it competes
   * with the English original for the same terms. `follow` so its links still
   * pass authority; the page leaves noindex by itself the moment its translation
   * completes and TRANSLATED_PAGES picks it up. */
  const indexable = locale !== 'fr' || TRANSLATED_PAGES.has(file);
  return [
    `<link rel="canonical" href="${canonical}" />`,
    `<meta name="robots" content="${indexable ? 'index, follow' : 'noindex, follow'}" />`,
    ...(kw && kw.length ? [`<meta name="keywords" content="${esc(kw.join(', '))}" />`] : []),
    ...hreflangTags(file),
    ...FAVICON_TAGS,
    `<meta property="og:type" content="website" />`,
    `<meta property="og:site_name" content="Davnoot" />`,
    `<meta property="og:title" content="${esc(title)}" />`,
    `<meta property="og:description" content="${esc(desc)}" />`,
    `<meta property="og:url" content="${canonical}" />`,
    `<meta property="og:image" content="${OG_IMAGE}" />`,
    // og:locale rides WITH its alternate, on the bilingual pages only. Emitting it
    // on the 37 English-only pages too would be defensible, but it would rewrite
    // every page on the site — and every one of those bytes would have to be
    // re-frozen and re-reviewed for a tag that tells a crawler nothing it cannot
    // already see from `lang`. Scope stays on the pages this feature is about.
    ...(TRANSLATED_PAGES.has(file)
      ? [
          `<meta property="og:locale" content="${locale === 'fr' ? 'fr_CA' : 'en_CA'}" />`,
          `<meta property="og:locale:alternate" content="${locale === 'fr' ? 'en_CA' : 'fr_CA'}" />`,
        ]
      : []),
    `<meta name="twitter:card" content="summary_large_image" />`,
    `<meta name="twitter:title" content="${esc(title)}" />`,
    `<meta name="twitter:description" content="${esc(desc)}" />`,
    `<meta name="twitter:image" content="${OG_IMAGE}" />`,
    `<script type="application/ld+json">\n${jsonLd(file, title, desc, faqs, locale)}\n</script>`,
  ].join('\n');
}
