/* AUTO-GENERATED by scripts/i18n.js — do not edit by hand.
 * The pages whose French translation is 100% COMPLETE, measured by
 * comparing every translatable unit against lib/i18n/fr.json.
 *
 * lib/templates.js turns this into TRANSLATED_PAGES, which drives hreflang,
 * the sitemap, the nav/footer hrefs and the language switcher. A page that is
 * only PARTLY translated must never appear here: it would be advertised to
 * Google as the French alternate of a page it is still mostly a copy of.
 *
 * Regenerate with `npm run site` and COMMIT the result. */
export const FULLY_TRANSLATED = [
  "index.html",
  "seo.html",
  "meta-ads.html",
  "email.html",
  "ai-seo.html",
  "chatgpt-ads.html",
  "software.html",
  "book-call.html"
];
