#!/usr/bin/env node
/* Minify the marketing site's CSS and JS.
 *
 *   npm run assets      (also runs inside `npm run site`)
 *
 *   styles.css  ->  styles.min.css
 *   blog.css    ->  blog.min.css
 *   script.js   ->  script.min.js
 *
 * WHY
 * ---
 * The 2026-08-01 Semrush audit's single largest line item was "Unminified JavaScript
 * and CSS files": 145 failed checks, one per (page × asset), across all 59 crawled
 * pages. It was also the only one of them that costs real money — styles.css alone is
 * 154 kB of source, shipped verbatim to every visitor on every cold cache, on a site
 * whose whole pitch is that it knows how to make pages fast.
 *
 * WHY .min.* SIBLINGS AND NOT "MINIFY styles.css IN PLACE"
 * --------------------------------------------------------
 * styles.css and script.js are hand-edited every week. Making the file the browser
 * loads also the file a human edits means either editing minified CSS or renaming the
 * source to styles.src.css and having a GENERATED file sit at the name every existing
 * reference, bookmark, and note points at. Siblings keep the source readable and the
 * generated artefact obviously generated.
 *
 * THE FOOTGUN THIS CREATES, AND THE GUARD FOR IT
 * ----------------------------------------------
 * Same one the committed SPA bundles have: edit styles.css, forget to re-minify, and
 * the deployed site silently serves yesterday's CSS — with no build error anywhere,
 * because this project deliberately has no build step on Vercel (see the
 * `no-build-script` note in package.json). So every output is stamped with a hash of
 * its source, exactly like scripts/src-hash.js does for the dashboards, and
 * scripts/assets.test.js recomputes it. A stale .min file fails `npm test` instead of
 * shipping. `npm run site` runs this too, so the normal workflow can't forget.
 *
 * esbuild is already a devDependency (the dashboards use it) — no new tooling.
 */
import esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');

/* source -> minified sibling. Add a row here and the reference test
 * (scripts/assets.test.js) immediately requires that nothing still links the source. */
export const ASSETS = [
  { src: 'styles.css', out: 'styles.min.css', loader: 'css' },
  { src: 'blog.css', out: 'blog.min.css', loader: 'css' },
  { src: 'script.js', out: 'script.min.js', loader: 'js' },
];

/** sha256 of a source file's bytes — the freshness stamp. */
export const hashOf = (file) =>
  crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT, file))).digest('hex').slice(0, 16);

/** The banner every generated file carries, and assets.test.js looks for. */
export const bannerFor = (src, hash) => `/*${src}:${hash} — generated by scripts/minify-assets.js. Do not edit.*/`;

/** Read the stamp out of a generated file, or null if it has none. */
export function stampIn(outFile) {
  const p = path.join(ROOT, outFile);
  if (!fs.existsSync(p)) return null;
  const head = fs.readFileSync(p, 'utf8').slice(0, 200);
  const m = /^\/\*([^:]+):([0-9a-f]+)/.exec(head);
  return m ? { src: m[1], hash: m[2] } : null;
}

export async function minifyAll({ quiet = false } = {}) {
  const report = [];
  for (const { src, out, loader } of ASSETS) {
    const code = fs.readFileSync(path.join(ROOT, src), 'utf8');
    const result = await esbuild.transform(code, {
      loader,
      minify: true,
      // ES2020 for JS matches the dashboards' target; `legalComments: none` drops the
      // source's own block comments, which is most of what makes styles.css 154 kB.
      target: loader === 'js' ? 'es2020' : 'chrome80',
      legalComments: 'none',
    });

    const body = bannerFor(src, hashOf(src)) + '\n' + result.code;
    fs.writeFileSync(path.join(ROOT, out), body);

    const before = Buffer.byteLength(code);
    const after = Buffer.byteLength(body);
    report.push({ src, out, before, after });
    if (!quiet) {
      console.log(
        `  ✓ ${out} — ${(before / 1024).toFixed(1)} kB → ${(after / 1024).toFixed(1)} kB ` +
          `(−${Math.round((1 - after / before) * 100)}%)`,
      );
    }
  }
  return report;
}

// Run only when invoked directly, so the test can import ASSETS/hashOf without
// rewriting the repo as a side effect of `import`.
if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
  await minifyAll();
}
