/* GET /sitemap.xml — every indexable URL on the site.
 *
 * Served via a rewrite in vercel.json. There is deliberately no sitemap.xml on
 * disk: a static file would shadow the rewrite and the blog posts would never be
 * submitted to Google.
 *
 * THREE SOURCES, IN DESCENDING ORDER OF RELIABILITY
 * -------------------------------------------------
 *  1. The 8 CMS marketing pages — from COMPILED_PAGES, a plain ESM import that is
 *     bundled into this function and CANNOT FAIL. Their per-page sitemap settings
 *     (include/priority/changefreq) and lastmod are OVERLAID from Mongo inside a
 *     try/catch. If Mongo is down, all 8 URLs are still emitted with their
 *     compiled defaults.
 *
 *     This is not a nicety — it is the reason the migration is safe. build.js used
 *     to enumerate the sitemap with readdirSync() over the repo root, so the moment
 *     a page was `git mv`'d into pages/ it would have SILENTLY DROPPED OUT OF THE
 *     SITEMAP, and lazily-created page documents mean Mongo would not have had it
 *     either. Every cutover would have quietly de-listed its own page.
 *
 *  2. The non-CMS static pages (ai-seo-agency.html, ai-seo-montreal.html) — from
 *     lib/sitemap-static.js, still generated by build.js. These are ordinary root
 *     .html files with no pages/ counterpart.
 *
 *  3. Composed pages (created in /admin, base:null) and published blog posts —
 *     from Mongo. These are the only entries that a Mongo outage can drop, and
 *     neither is a revenue URL.
 *
 * lastmod is NEVER `new Date()`. A sitemap whose lastmod churns on every fetch
 * teaches Google to ignore the field entirely.
 */
import { posts, pages } from '../lib/db.js';
import { publishedFilter } from '../lib/blog-query.js';
import { SITE_URL } from '../lib/templates.js';
import { STATIC_URLS } from '../lib/sitemap-static.js';
import { COMPILED_PAGES } from '../lib/compiled-pages.gen.js';
import { isPageLive } from '../lib/page-model.js';

const BLOG_INDEX = SITE_URL + '/blog';

// Bound every Mongo read the way api/page.js does. lib/db.js also sets a 2s
// serverSelectionTimeoutMS, but a query that connects fast and then hangs would
// still block past the function's maxDuration and return a PLATFORM 5xx — which
// would defeat this route's whole "the marketing URLs cannot fail" guarantee. So
// we race each read against a timeout and degrade to compiled defaults instead.
const rejectAfter = (ms) =>
  new Promise((_, reject) => setTimeout(() => reject(new Error('mongo-timeout')), ms));
const bounded = (promise, ms = 2500) => Promise.race([promise, rejectAfter(ms)]);

const day = (d) => {
  const date = d instanceof Date ? d : d ? new Date(d) : null;
  return date && !Number.isNaN(date.getTime()) ? date.toISOString().slice(0, 10) : undefined;
};

const escXml = (s) =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');

function urlEntry({ loc, lastmod, changefreq, priority }) {
  return `  <url>
    <loc>${escXml(loc)}</loc>${lastmod ? `\n    <lastmod>${lastmod}</lastmod>` : ''}${
      changefreq ? `\n    <changefreq>${changefreq}</changefreq>` : ''
    }${priority ? `\n    <priority>${priority}</priority>` : ''}
  </url>`;
}

/* The compiled-in defaults, mirroring build.js's sitemapMeta(). Home ranks highest;
 * the booking page slightly below the service pages. */
function defaultMeta(file) {
  if (file === 'index.html') return { priority: '1.0', changefreq: 'weekly' };
  if (file === 'book-call.html') return { priority: '0.7', changefreq: 'monthly' };
  return { priority: '0.8', changefreq: 'monthly' };
}

/**
 * The 8 CMS marketing pages. `docs` may be empty (Mongo down) — every URL is still
 * emitted, because the template is compiled into this function.
 *
 * Exclusion rules, in order:
 *   status 'archived'        -> the page 410s. Drop it, and let Google forget it.
 *   sitemap.include === false -> the author excluded it explicitly.
 *   seo.robotsIndex === false -> noindex. Advertising a noindexed URL is a
 *                                contradiction Search Console reports as an error.
 *
 * A page with NO document, or a doc whose edits are not yet published, is still
 * LIVE — api/page.js falls back to the base template and serves today's exact
 * bytes. So it stays in the sitemap. (This is the whole point of the overlay model:
 * "draft" on one of the 8 means "edits not live", never "page not live".)
 */
function marketingEntries(byPath, now) {
  const out = [];
  for (const tpl of Object.values(COMPILED_PAGES)) {
    const doc = byPath.get(tpl.path);
    if (doc?.status === 'archived') continue;

    // Only PUBLISHED content contributes overrides. An unpublished draft must not
    // change what we advertise, because it is not what a crawler will be served.
    const live = isPageLive(doc, now) ? doc.live || {} : {};
    const sm = live.sitemap || {};
    if (sm.include === false) continue;
    if (live.seo?.robotsIndex === false) continue;

    const def = defaultMeta(tpl.file);
    out.push({
      loc: SITE_URL + tpl.path,
      // lastmod is a PUBLISH-time signal, never a draft-edit one. buildDraftUpdate()
      // bumps doc.updatedAt on every 900ms autosave keystroke, so keying lastmod off
      // updatedAt would churn the live page's lastmod while a draft nobody has
      // published sits in the editor — teaching Google to ignore the field. publishedAt
      // moves only on an actual publish. Falls back to the page's compiled date.
      lastmod: (isPageLive(doc, now) && day(doc.publishedAt)) || tpl.compiledAt,
      changefreq: sm.changefreq || def.changefreq,
      priority: sm.priority || def.priority,
    });
  }
  return out;
}

/** Composed pages built in /admin (base:null). Live + published + indexable only. */
function composedEntries(docs, now) {
  const out = [];
  for (const doc of docs) {
    if (doc.base !== null && doc.base !== undefined) continue; // overlay pages handled above
    if (!isPageLive(doc, now)) continue; // draft or scheduled -> api/page.js 404s it
    const live = doc.live || {};
    const sm = live.sitemap || {};
    if (sm.include === false) continue;
    if (live.seo?.robotsIndex === false) continue;
    out.push({
      loc: SITE_URL + doc.path,
      lastmod: day(doc.updatedAt) || day(doc.publishedAt),
      changefreq: sm.changefreq || 'monthly',
      priority: sm.priority || '0.6',
    });
  }
  return out;
}

export default async function handler(req, res) {
  const now = new Date();

  // ---- 1 + 3a. Pages. The marketing half survives a total Mongo outage. ----
  let pageDocs = [];
  let pagesDegraded = false;
  try {
    pageDocs = await bounded(
      (async () =>
        (await pages())
          .find({}, { projection: { path: 1, base: 1, status: 1, publishedAt: 1, updatedAt: 1, 'live.sitemap': 1, 'live.seo.robotsIndex': 1 } })
          .limit(2000)
          .toArray())(),
    );
  } catch (err) {
    pagesDegraded = true;
    console.error('[sitemap] pages unavailable, using compiled defaults:', err?.message || err);
  }

  const byPath = new Map(pageDocs.map((d) => [d.path, d]));
  const entries = [
    ...marketingEntries(byPath, now), // always all 8 (minus archived/noindex/excluded)
    ...STATIC_URLS, // the non-CMS root pages
    ...composedEntries(pageDocs, now),
  ];

  // ---- 3b. The blog. ----
  let blogCount = 0;
  try {
    const docs = await bounded(
      (async () =>
        (await posts())
          .find(publishedFilter(), { projection: { slug: 1, publishedAt: 1, updatedAt: 1 } })
          .sort({ publishedAt: -1 })
          .limit(5000)
          .toArray())(),
    );

    if (docs.length) {
      entries.push({
        loc: BLOG_INDEX,
        lastmod: day(docs[0].publishedAt),
        changefreq: 'weekly',
        priority: '0.9',
      });

      for (const doc of docs) {
        entries.push({
          loc: `${BLOG_INDEX}/${doc.slug}`,
          lastmod: day(doc.updatedAt) || day(doc.publishedAt),
          changefreq: 'monthly',
          priority: '0.7',
        });
      }
      blogCount = docs.length;
    }
  } catch (err) {
    // Degrade gracefully — serve the pages rather than failing the whole sitemap.
    console.error('[sitemap] could not read posts, serving pages only:', err);
  }

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${Object.keys(COMPILED_PAGES).length} CMS page(s) from COMPILED_PAGES${pagesDegraded ? ' (Mongo unavailable — compiled defaults)' : ''} + ${STATIC_URLS.length} static + ${blogCount} published post(s). -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.map(urlEntry).join('\n')}
</urlset>
`;

  res.setHeader('Content-Type', 'application/xml; charset=utf-8');
  // A degraded sitemap must not be cached for long — it is missing the blog.
  res.setHeader(
    'Cache-Control',
    pagesDegraded ? 'public, s-maxage=60' : 'public, s-maxage=600, stale-while-revalidate=3600',
  );
  return res.status(200).send(xml);
}
